global:
  name: consul
  datacenter: dc1
  image: "consul:latest"
  imageEnvoy: envoyproxy/envoy-alpine:v1.20.0
client:
  enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  affinity: ""
  storageClass: ""
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: false
    runAsUser: 0
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
prometheus:
  enabled: true
grafana:
  enabled: true
connect:
  enabled: true
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
    service:
      type: "NodePort"
      ports:
        - port: 8080
          nodePort: 30080
        - port: 8443
          nodePort: 30443
  gateways:
    - name: "ingress-gateway"
